### ISSUE TITLE
feat: generate interfaces from resources

### ISSUE THREAD

**Issue by ibrunotome** [lepikhinb/laravel-typescript#1]
Hi! What do you think about generation from Resources? e.g:

```php
/**
 * @mixin \App\Models\Ticket
 */
class SupportResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request): array
    {
        return [
            'id'         => $this->id,
            'title'      => $this->title,
            'message'    => $this->message,
            'created_at' => $this->created_at->diffForHumans(),
            'category'   => [
                'title' => $this->category->short_title,
                'hex_color'   => $this->category->hex_color,
            ],
            'status'     => [
                'title'     => $this->status->title,
                'hex_color' => $this->status->hex_color,
            ],
        ];
    }
}
```

It's possible? If it is, it will be a consistent interface in the backend and frontend.

**Comment by lepikhinb** [comment]
This one would be kinda tricky, as it probably requires the actual token parsing. However, I'll try to get back to this.

**Comment by lepikhinb** [comment]
Closing for a while.

**Comment by GENL** [comment]
It would be great,

**Comment by sawirricardo** [comment]
@lepikhinb any update on this? This one will be good since many of us use laravel resource

**Comment by neoighodaro** [comment]
Any update? Would be nice to have this tbh

**Comment by mxaGianluca** [comment]
I’ve had a stab at this and created a package that tries to solve this, i’m not sure if it’s bad practice to share it here that’s why I’d like to ask it first. (If it is, feel free to remove my comment)
